name: MetaFOX

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "15671:15671"
      - "15672:15672"
      - "15691:15691"
      - "15692:15692"
      - "25672:25672"
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

  api:
    build:
      context: ./src/metafox_api
      dockerfile: Dockerfile
    container_name: api
    environment:
        BROKER_URL: pyamqp://rabbitmq:5672//
        RESULT_BACKEND: mongodb://mongo:27017/
        TASK_SERIALIZER: json
        RESULT_SERIALIZER: json
        WORKER_CONCURRENCY: 1
        KEYCLOAK_SERVER_URL:
        KEYCLOAK_CLIENT_ID:
        KEYCLOAK_REALM_NAME:
        KEYCLOAK_CLIENT_SECRET:
        KEYCLOAK_AUTHORIZATION_URL:
        KEYCLOAK_TOKEN_URL:
        KEYCLOAK_REFRESH_URL:
        CORS_ORIGINS:
        API_AUTH_ENABLED: "False"
        API_ORIGINS: "*"
        API_ALLOW_CREDENTIALS: "True"
        API_ALLOW_METHODS: "*"
        API_ALLOW_HEADERS: "*"
        RESULT_EXPIRES: 0
        MONGO_DB: metafox
        MONGO_URI: mongodb://mongo:27017/
        MONGO_COLLECTION_TASK_META: task_meta
        MONGO_COLLECTION_AUTOML_JOB_DETAILS: automl_job_details
        MONGO_COLLECTION_TASK_INFO: task_info
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - mongo
    volumes:
      - ./src/metafox_shared:/usr/src/metafox_shared

  worker:
    build:
      context: ./src/metafox_worker
      dockerfile: Dockerfile
    environment:
        BROKER_URL: pyamqp://rabbitmq:5672//
        RESULT_BACKEND: mongodb://mongo:27017/
        TASK_SERIALIZER: json
        RESULT_SERIALIZER: json
        WORKER_CONCURRENCY: 1
        RESULT_EXPIRES: 0
        MONGO_DB: metafox
        MONGO_URI: mongodb://mongo:27017/
        MONGO_COLLECTION_TASK_META: task_meta
        MONGO_COLLECTION_AUTOML_JOB_DETAILS: automl_job_details
        MONGO_COLLECTION_TASK_INFO: task_info
    depends_on:
      - api
      - rabbitmq
      - mongo
    volumes:
      - ./src/metafox_shared:/usr/src/metafox_shared
    deploy:
      replicas: 4

  flower:
    image: mher/flower
    container_name: flower
    environment:
        BROKER_URL: pyamqp://rabbitmq:5672//
        RESULT_BACKEND: mongodb://mongo:27017/
        FLOWER_PERSISTENT: True
        FLOWER_STATE_SAVE_INTERVAL: 10000
        FLOWER_DB: flower_db
    ports:
      - "5555:5555"
    depends_on:
      - api
      - rabbitmq
      - mongo