# k8s/flower_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flower
  template:
    metadata:
      labels:
        app: flower
    spec:
      containers:
      - name: flower
        image: mher/flower
        env:
        - name: BROKER_URL
          value: "pyamqp://rabbitmq:5672//"
        - name: RESULT_BACKEND
          value: "redis://redis:6379/0"
        - name: FLOWER_PERSISTENT
          value: "True"
        - name: FLOWER_STATE_SAVE_INTERVAL
          value: "10000"
        - name: FLOWER_DB
          value: "flower_db"
        ports:
        - containerPort: 5555