# k8s/flower_service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flower-service
spec:
  selector:
    app: flower
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
      nodePort: 30002
  type: NodePort