# filepath: /home/drashko/CERAMO/metafox/k8s/metafox_worker_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metafox-worker
spec:
  replicas: 4
  selector:
    matchLabels:
      app: metafox-worker
  template:
    metadata:
      labels:
        app: metafox-worker
    spec:
      containers:
      - name: metafox-worker
        image: drashkko/metafox-worker:latest
        env:
        - name: BROKER_URL
          value: "pyamqp://rabbitmq:5672//"
        - name: RESULT_BACKEND
          value: "mongodb://mongo:27017/"
        - name: WORKER_CONCURRENCY
          value: "1"
        - name: MONGO_DB
          value: "metafox"
        - name: MONGO_URI
          value: "mongodb://mongo:27017/"
        - name: MONGO_COLLECTION_TASK_META
          value: "task_meta"
        - name: MONGO_COLLECTION_AUTOML_JOB_DETAILS
          value: "automl_job_details"
        - name: MONGO_COLLECTION_TASK_INFO
          value: "task_info"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        - name: DB_TYPE
          value: "redis"
        - name: PYTHONPATH
          value: "/usr/src"